In [13]:
import pandas as pd

dataset = pd.read_csv("../housing.csv")

X = dataset.drop("median_house_value", axis=1)
Y = dataset["median_house_value"]

print(X.describe(include="all"))
print("\n")
print("Total missing values\n", X.isnull().sum())

           longitude      latitude  housing_median_age   total_rooms  \
count   20640.000000  20640.000000        20640.000000  20640.000000
unique           NaN           NaN                 NaN           NaN
top              NaN           NaN                 NaN           NaN
freq             NaN           NaN                 NaN           NaN
mean     -119.569704     35.631861           28.639486   2635.763081
std         2.003532      2.135952           12.585558   2181.615252
min      -124.350000     32.540000            1.000000      2.000000
25%      -121.800000     33.930000           18.000000   1447.750000
50%      -118.490000     34.260000           29.000000   2127.000000
75%      -118.010000     37.710000           37.000000   3148.000000
max      -114.310000     41.950000           52.000000  39320.000000

        total_bedrooms    population    households  median_income  \
count     20433.000000  20640.000000  20640.000000   20640.000000
unique             NaN           NaN           NaN            NaN
top                NaN           NaN           NaN            NaN
freq               NaN           NaN           NaN            NaN
mean        537.870553   1425.476744    499.539680       3.870671
std         421.385070   1132.462122    382.329753       1.899822
min           1.000000      3.000000      1.000000       0.499900
25%         296.000000    787.000000    280.000000       2.563400
50%         435.000000   1166.000000    409.000000       3.534800
75%         647.000000   1725.000000    605.000000       4.743250
max        6445.000000  35682.000000   6082.000000      15.000100

       ocean_proximity
count            20640
unique               5
top          <1H OCEAN
freq              9136
mean               NaN
std                NaN
min                NaN
25%                NaN
50%                NaN
75%                NaN
max                NaN


Total missing values
 longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [19]:
from sklearn.impute import SimpleImputer

num_columns = X.select_dtypes(include=["float64", "int64"],).columns
print(num_columns)
imputer = SimpleImputer(strategy="median")
X[num_columns] = imputer.fit_transform(X[num_columns])

cat_columns = ["ocean_proximity"]
cat_imputer = SimpleImputer(strategy="most_frequent")
X[cat_columns] = cat_imputer.fit_transform(X[cat_columns])

print(X.describe(include="all"))

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype='object')
           longitude      latitude  housing_median_age   total_rooms  \
count   20640.000000  20640.000000        20640.000000  20640.000000
unique           NaN           NaN                 NaN           NaN
top              NaN           NaN                 NaN           NaN
freq             NaN           NaN                 NaN           NaN
mean     -119.569704     35.631861           28.639486   2635.763081
std         2.003532      2.135952           12.585558   2181.615252
min      -124.350000     32.540000            1.000000      2.000000
25%      -121.800000     33.930000           18.000000   1447.750000
50%      -118.490000     34.260000           29.000000   2127.000000
75%      -118.010000     37.710000           37.000000   3148.000000
max      -114.310000     41.950000           52.000000  39320.000000

        total_bedrooms    population    households  median_income  \
count     20640.000000  20640.000000  20640.000000   20640.000000
unique             NaN           NaN           NaN            NaN
top                NaN           NaN           NaN            NaN
freq               NaN           NaN           NaN            NaN
mean        536.838857   1425.476744    499.539680       3.870671
std         419.391878   1132.462122    382.329753       1.899822
min           1.000000      3.000000      1.000000       0.499900
25%         297.000000    787.000000    280.000000       2.563400
50%         435.000000   1166.000000    409.000000       3.534800
75%         643.250000   1725.000000    605.000000       4.743250
max        6445.000000  35682.000000   6082.000000      15.000100

       ocean_proximity
count            20640
unique               5
top          <1H OCEAN
freq              9136
mean               NaN
std                NaN
min                NaN
25%                NaN
50%                NaN
75%                NaN
max                NaN

In [21]:
X = pd.get_dummies(X, cat_columns, drop_first=True)

print(X.describe(include="all"))

           longitude      latitude  housing_median_age   total_rooms  \
count   20640.000000  20640.000000        20640.000000  20640.000000
unique           NaN           NaN                 NaN           NaN
top              NaN           NaN                 NaN           NaN
freq             NaN           NaN                 NaN           NaN
mean     -119.569704     35.631861           28.639486   2635.763081
std         2.003532      2.135952           12.585558   2181.615252
min      -124.350000     32.540000            1.000000      2.000000
25%      -121.800000     33.930000           18.000000   1447.750000
50%      -118.490000     34.260000           29.000000   2127.000000
75%      -118.010000     37.710000           37.000000   3148.000000
max      -114.310000     41.950000           52.000000  39320.000000

        total_bedrooms    population    households  median_income  \
count     20640.000000  20640.000000  20640.000000   20640.000000
unique             NaN           NaN           NaN            NaN
top                NaN           NaN           NaN            NaN
freq               NaN           NaN           NaN            NaN
mean        536.838857   1425.476744    499.539680       3.870671
std         419.391878   1132.462122    382.329753       1.899822
min           1.000000      3.000000      1.000000       0.499900
25%         297.000000    787.000000    280.000000       2.563400
50%         435.000000   1166.000000    409.000000       3.534800
75%         643.250000   1725.000000    605.000000       4.743250
max        6445.000000  35682.000000   6082.000000      15.000100

       ocean_proximity_INLAND ocean_proximity_ISLAND ocean_proximity_NEAR BAY  \
count                   20640                  20640                    20640
unique                      2                      2                        2
top                     False                  False                    False
freq                    14089                  20635                    18350
mean                      NaN                    NaN                      NaN
std                       NaN                    NaN                      NaN
min                       NaN                    NaN                      NaN
25%                       NaN                    NaN                      NaN
50%                       NaN                    NaN                      NaN
75%                       NaN                    NaN                      NaN
max                       NaN                    NaN                      NaN

       ocean_proximity_NEAR OCEAN
count                       20640
unique                          2
top                         False
freq                        17982
mean                          NaN
std                           NaN
min                           NaN
25%                           NaN
50%                           NaN
75%                           NaN
max                           NaN